version: '3.4'

services:
  stackoverflowtagapi:
    image: ${DOCKER_REGISTRY-}stackoverflowtagapi
    build:
      context: .
      dockerfile: StackOverflow tag API/Dockerfile
    depends_on:
      - mssql
    ports:
        - "8080:80"
        - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=443
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
       - "1433:1433"